// <auto-generated />
using System;
using EmployeeService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeService.Migrations;

[DbContext(typeof(EmployeeDbContext))]
partial class EmployeeDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("EmployeeService.Domain.Entities.Department", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<bool>("IsActive").HasColumnType("bit");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Departments");
        });

        modelBuilder.Entity("EmployeeService.Domain.Entities.Employee", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<int>("DepartmentId").HasColumnType("int");
            b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<DateTime>("HireDate").HasColumnType("datetime2");
            b.Property<bool>("IsActive").HasColumnType("bit");
            b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Phone").HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("Position").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("ProfilePictureUrl").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<decimal>("Salary").HasColumnType("decimal(18,2)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("DepartmentId");
            b.ToTable("Employees");
        });

        modelBuilder.Entity("EmployeeService.Domain.Entities.EmployeeDocument", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("BlobName").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("BlobUrl").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<string>("ContentType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<int>("EmployeeId").HasColumnType("int");
            b.Property<string>("FileName").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
            b.Property<long>("FileSize").HasColumnType("bigint");
            b.Property<bool>("IsDeleted").HasColumnType("bit");
            b.Property<string>("OriginalFileName").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
            b.Property<DateTime>("UploadedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("EmployeeId");
            b.ToTable("EmployeeDocuments");
        });

        modelBuilder.Entity("EmployeeService.Domain.Entities.ApplicationUser", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<bool>("IsActive").HasColumnType("bit");
            b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime2");
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("Username").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("EmployeeService.Domain.Entities.Employee", b =>
        {
            b.HasOne("EmployeeService.Domain.Entities.Department", "Department")
                .WithMany("Employees")
                .HasForeignKey("DepartmentId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.Navigation("Department");
        });

        modelBuilder.Entity("EmployeeService.Domain.Entities.EmployeeDocument", b =>
        {
            b.HasOne("EmployeeService.Domain.Entities.Employee", "Employee")
                .WithMany("Documents")
                .HasForeignKey("EmployeeId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Employee");
        });

        modelBuilder.Entity("EmployeeService.Domain.Entities.Department", b =>
        {
            b.Navigation("Employees");
        });

        modelBuilder.Entity("EmployeeService.Domain.Entities.Employee", b =>
        {
            b.Navigation("Documents");
        });
#pragma warning restore 612, 618
    }
}
