apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: employee-mgmt
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: employee-mgmt/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: JwtSettings__Secret
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JwtSettings__Secret
            - name: JwtSettings__Issuer
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JwtSettings__Issuer
            - name: JwtSettings__Audience
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JwtSettings__Audience
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/live
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
