apiVersion: v1
kind: Service
metadata:
  name: department-service
  namespace: employee-mgmt
  labels:
    app: department-service
spec:
  selector:
    app: department-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 30003
  type: NodePort
