apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: employee-mgmt
  labels:
    app: employee-service
spec:
  selector:
    app: employee-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002
  type: NodePort
